#!/bin/bash

. ~/.bashrc

if [[ $# -eq 0 ]]
then
	echo "Usage: ${0##git-shell-commands/} <project.git>"
	exit 1
fi

repo="${1%%.git}".git

if [[ -d "$repo" ]] 
then 
	echo "Error! Repo $repo already exists"
	exit 1
fi

cd $REPOS &&
    mkdir -p "$repo" &&
    git init -q --bare --initial-branch=main "$repo" &&
    printf "ssh://%s@%s:%d%s/%s\n" "$USER" "$(hostname -f)" "${EXT_PORT}" "$REPOS" "$repo"
